png(file = "plot1.png")
data <- read.table("household_power_consumption.txt", sep=";", header = TRUE, na.strings = "?")
data$Time <- strptime(data$Time, format = "%H:%M:%S")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data <- subset(data, Date >= '2007-02-01' & Date <= '2007-02-02')
hist(data$Global_active_power, col = "Red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()